server:
  port: 8000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
spring:
  application:
    name: OpenAiChatService
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 12MB
      max-request-size: 20MB
  cloud:
    bootstrap:
      enabled: true
    config:
      profile: dev
      discovery:
        enabled: true
        service-id: ConfigService
      enabled: true

  config:
    import: optional:configserver:http://localhost:8887

  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.vectorstore.weaviate.WeaviateVectorStoreAutoConfiguration
      - org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
    com.amazonaws: DEBUG
    io.awspring.cloud: DEBUG

